version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.9.5  # primary container for the build job
      - image: selenium/standalone-chrome:3.11.0
        auth:
          username: carvivocircleci
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            pip install pipenv
            pipenv install
            pip install selenium
            pip install chromedriver-py
            pip install chromedriver_installer \
                --install-option="--chromedriver-version=2.10" \
                --install-option="--chromedriver-checksums=4fecc99b066cb1a346035bf022607104,058cd8b7b4b9688507701b5e648fd821"
      - run:
          command: |
            python Katalon.py