version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.9.5  # primary container for the build job
      - image: selenium/standalone-chrome:3.11.0
        auth:
          username: carvivocircleci
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout  # checkout source code to working directory cc
      - run:
          command: |  # use pipenv to install dependencies  python3 -m pip install pipenv pipenv install
            sudo python3 -m pip install --upgrade pip
            python3 -m pip install pip
            pip install -U selenium
            python3 -m venv venv
            . venv/bin/activate
      - run:
          command: |
            python C:\Users\Chloe\PycharmProjects\CarvivoCoKatalonS\Katalon.py