version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.6.2-stretch-browsers  # primary container for the build job
        auth:
          username: carvivocircleci
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout  # checkout source code to working directory cc
      - run:
            name: Download Selenium
            command: |
              curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
            name: Start Selenium
            command: |
              java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
            background: true
      - run:
          command: |  # use pipenv to install dependencies  python3 -m pip install pipenv pipenv install
            sudo python3 -m pip install --upgrade pip
            pip install -U selenium
            python3 -m venv venv
            . venv/bin/activate
      - run:
          command: |
            python Katalon.py