version: 2
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/python:3.6.2-stretch-browsers  # primary container for the build job
        auth:
          username: carvivocircleci
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout  # checkout source code to working directory cc
      - run: mkdir test-reports
      - run:
            name: Download Selenium
            command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Download python
          command: |  # use pipenv to install dependencies  python3 -m pip install pipenv pipenv install
            sudo python3 -m pip install --upgrade pip
            pip install -U selenium
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: Lancer test
          command: |
            python Katalon.py
      - store_artifacts:
          path: test-reports