version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.9.5  # primary container for the build job
        auth:
          username: carvivocircleci
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            pip install pipenv
            pipenv install
            pip install selenium
      - run:
          command: |
            pipenv run python Katalon.py test